### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by sakrist** [wzqcongcong/MacGuarder#2]
Trying to build app from sources, but not fails on RNCryptor. 
What version of RNCryptor I need to use?
thanks

**Comment by wzqcongcong** [comment]
The latest RNCryptor seems not able to support bridge to Objective-C:

https://github.com/RNCryptor/RNCryptor

"RNCryptor 5 is written in Swift 3 and does not bridge to Objective-C (it includes features that are not available). If you want an ObjC implementation, see [RNCryptor-objc](https://github.com/RNCryptor/RNCryptor-objc). That version can be accessed from Swift, or both versions can coexist in the same project."

So please try [RNCryptor-objc](https://github.com/RNCryptor/RNCryptor-objc). I will update the pods later. :)

**Comment by sakrist** [comment]
Actually I've fixed on my side with pod you mentioned :) thanks
